version: "3.5"

services:
  api1:
    image: rnavarro/rinha-backend-axum:1
    hostname: api1
    environment:
      PORT: 80
      DATABASE_URL: postgres://rinha:rinha@db/rinha
    depends_on:
      - db
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"

  api2:
    image: rnavarro/rinha-backend-axum:1
    hostname: api2
    environment:
      PORT: 80
      DATABASE_URL: postgres://rinha:rinha@db/rinha
    depends_on:
      - db
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "0.5GB"

  db:
    image: postgres:15
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    command: postgres -c log_min_messages=FATAL
    environment:
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
      POSTGRES_DB: rinha
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "1.5GB"
