name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    name: Publish to Dockerhub
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lib:
          - { dockerfile: rinha-axum/Dockerfile, image: rinha-backend-axum }
          - { dockerfile: rinha-touche/Dockerfile, image: rinha-backend-touche }
    steps:
      - uses: actions/checkout@v2

      - name: Get release version
        id: get_version
        uses: battila7/get-version-action@v2

      - run: docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_PASS }}

      - run: docker build -f ${{ matrix.lib.dockerfile }} -t rinha .
      - run: docker tag rinha rnavarro/${{ matrix.lib.image }}:latest
      - run: docker tag rinha rnavarro/${{ matrix.lib.image }}:${{ steps.get_version.outputs.major }}
      - run: docker tag rinha rnavarro/${{ matrix.lib.image }}:${{ steps.get_version.outputs.major }}.${{ steps.get_version.outputs.minor }}
      - run: docker tag rinha rnavarro/${{ matrix.lib.image }}:${{ steps.get_version.outputs.version-without-v }}

      - run: docker push rnavarro/${{ matrix.lib.image }}:latest
      - run: docker push rnavarro/${{ matrix.lib.image }}:${{ steps.get_version.outputs.major }}
      - run: docker push rnavarro/${{ matrix.lib.image }}:${{ steps.get_version.outputs.major }}.${{ steps.get_version.outputs.minor }}
      - run: docker push rnavarro/${{ matrix.lib.image }}:${{ steps.get_version.outputs.version-without-v }}
